workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      # groups:
        # Add your environment variables group name here
        # - app_store_credentials # Uncomment and configure in Codemagic UI
        # Environment variables should be configured in Codemagic UI under Environment Variables
        
    # Cache configuration
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.cocoapods
        - $HOME/.gradle/caches
        - Pods
        - ios/Pods
        - ios/Flutter/Flutter.framework
        - ios/Flutter/Flutter.podspec

    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
          
      - name: Clean iOS build
        script: |
          flutter clean
          cd ios
          rm -rf Pods Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          rm -rf build/
          cd ..
          
      - name: Get Flutter dependencies
        script: |
          flutter pub get
          
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod deintegrate || true
          pod cache clean --all || true
          pod install --repo-update
          cd ..
          
      - name: Create privacy manifest placeholders after pod install
        script: |
          # Create privacy manifest files immediately after pod install
          # This ensures they exist before Xcode tries to use them as build inputs
          echo "Creating privacy manifest placeholders..."
          
          CRITICAL_PACKAGES="url_launcher_ios sqflite_darwin shared_preferences_foundation path_provider_foundation flutter_secure_storage flutter_local_notifications share_plus"
          
          # Create in build directory
          BUILD_DIR="build/ios/Release-iphoneos"
          mkdir -p "$BUILD_DIR"
          
          for package in $CRITICAL_PACKAGES; do
            BUNDLE_DIR="${BUILD_DIR}/${package}_privacy.bundle"
            mkdir -p "$BUNDLE_DIR"
            touch "${BUNDLE_DIR}/${package}_privacy"
            chmod 644 "${BUNDLE_DIR}/${package}_privacy"
            echo "Created placeholder: ${BUNDLE_DIR}/${package}_privacy"
          done
          
      - name: Verify Podfile script phases
        script: |
          # Verify that Podfile has privacy manifest script phases
          # The Podfile script phase should handle all packages automatically
          echo "Checking Podfile for privacy manifest script phases..."
          if grep -q "Create Privacy Manifest" ios/Podfile; then
            echo "✓ Podfile contains privacy manifest script phases"
          else
            echo "⚠ Podfile might not have privacy manifest script phases"
          fi
          
      - name: Flutter analyze
        script: |
          # Run analyze but don't fail build on warnings/infos (only fail on actual errors)
          # Use || true to continue even if analyze finds issues
          flutter analyze --no-fatal-infos --no-fatal-warnings || true
          
      - name: Flutter test
        script: |
          flutter test || true  # Continue even if tests fail for now
          
      - name: Create privacy manifests right before build
        script: |
          # Create privacy manifest files immediately before build
          # For archive builds, Xcode looks in DerivedData/ArchiveIntermediates/UninstalledProducts
          # For regular builds, Xcode looks in build/ios/Release-iphoneos
          echo "Creating privacy manifest files right before build..."
          
          # List of packages that commonly need privacy manifests
          CRITICAL_PACKAGES="url_launcher_ios sqflite_darwin shared_preferences_foundation path_provider_foundation flutter_secure_storage flutter_local_notifications nanopb SDWebImage SwiftyGif share_plus"
          
          # Function to create privacy manifest for a package in a specific location
          create_privacy_manifest_in_dir() {
            local package=$1
            local base_dir=$2
            if [ -z "$package" ] || [ -z "$base_dir" ]; then
              return
            fi
            
            # Create privacy bundle directly (not in a package subdirectory for archive builds)
            BUNDLE_DIR="${base_dir}/${package}_privacy.bundle"
            mkdir -p "$BUNDLE_DIR"
            # Create an empty file - privacy bundles are resource-only and don't need a binary
            touch "${BUNDLE_DIR}/${package}_privacy" || true
            chmod 644 "${BUNDLE_DIR}/${package}_privacy" || true
            echo "Created: ${BUNDLE_DIR}/${package}_privacy"
          }
          
          # Create in regular build directory
          BUILD_DIR="build/ios/Release-iphoneos"
          mkdir -p "$BUILD_DIR"
          for package in $CRITICAL_PACKAGES; do
            create_privacy_manifest_in_dir "$package" "$BUILD_DIR"
          done
          
          # Also create in DerivedData locations (for archive builds)
          # Find the DerivedData directory for this project
          DERIVED_DATA_BASE="$HOME/Library/Developer/Xcode/DerivedData"
          if [ -d "$DERIVED_DATA_BASE" ]; then
            # Create privacy manifests in potential archive build locations
            for derived_dir in "$DERIVED_DATA_BASE"/*/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos; do
              if [ -d "$(dirname "$derived_dir")" ]; then
                mkdir -p "$derived_dir"
                for package in $CRITICAL_PACKAGES; do
                  create_privacy_manifest_in_dir "$package" "$derived_dir"
                done
                echo "Created privacy manifests in DerivedData location: $derived_dir"
              fi
            done
          fi
          
          # Verify critical packages
          echo "Verifying privacy manifests for critical packages..."
          for package in url_launcher_ios sqflite_darwin shared_preferences_foundation share_plus; do
            MANIFEST_PATH="${BUILD_DIR}/${package}_privacy.bundle/${package}_privacy"
            if [ -f "$MANIFEST_PATH" ]; then
              echo "✓ ${package} privacy manifest exists at: $MANIFEST_PATH"
            else
              echo "✗ ${package} privacy manifest NOT found at: $MANIFEST_PATH"
            fi
          done
          
          echo "Privacy manifest files created and verified"
          
      - name: Build iOS IPA
        script: |
          # Function to create privacy manifest files in all possible locations
          create_privacy_manifests() {
            # List of packages that need privacy manifests
            CRITICAL_PACKAGES="url_launcher_ios sqflite_darwin shared_preferences_foundation path_provider_foundation flutter_secure_storage flutter_local_notifications share_plus"
            
            # Create in regular build directory
            BUILD_DIR="build/ios/Release-iphoneos"
            mkdir -p "$BUILD_DIR"
            
            for package in $CRITICAL_PACKAGES; do
              # Create privacy bundle directly in build directory
              BUNDLE_DIR="${BUILD_DIR}/${package}_privacy.bundle"
              mkdir -p "$BUNDLE_DIR"
              touch "${BUNDLE_DIR}/${package}_privacy" || true
              chmod 644 "${BUNDLE_DIR}/${package}_privacy" || true
              echo "Created: ${BUNDLE_DIR}/${package}_privacy"
            done
            
            # Also create in DerivedData locations for archive builds
            # The error shows: DerivedData/Runner-*/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos
            DERIVED_DATA_BASE="$HOME/Library/Developer/Xcode/DerivedData"
            if [ -d "$DERIVED_DATA_BASE" ]; then
              # Find all Runner-* directories in DerivedData
              for derived_dir in "$DERIVED_DATA_BASE"/Runner-*/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos; do
                if [ -d "$(dirname "$derived_dir")" ]; then
                  mkdir -p "$derived_dir"
                  for package in $CRITICAL_PACKAGES; do
                    BUNDLE_DIR="${derived_dir}/${package}_privacy.bundle"
                    mkdir -p "$BUNDLE_DIR"
                    touch "${BUNDLE_DIR}/${package}_privacy" || true
                    chmod 644 "${BUNDLE_DIR}/${package}_privacy" || true
                    echo "Created in DerivedData: ${BUNDLE_DIR}/${package}_privacy"
                  done
                fi
              done
            fi
          }
          
          # Create privacy manifests before build
          create_privacy_manifests
          
          # Build IPA with export options
          # Note: This will create an archive, which is where the privacy bundle error occurs
          flutter build ipa --release --export-options-plist /Users/builder/export_options.plist 2>&1 | tee /tmp/flutter_build.log || BUILD_FAILED=1
            
          if [ "$BUILD_FAILED" = "1" ]; then
            echo "=========================================="
            echo "Build failed! Analyzing errors..."
            echo "=========================================="
            
            # Show errors from Flutter output
            echo ""
            echo "=== Errors in Flutter build output ==="
            grep -i "error\|failed\|cannot be found" /tmp/flutter_build.log | tail -20 || true
            
            # Check for Xcode build logs
            echo ""
            echo "=== Checking Xcode build logs ==="
            XCODE_LOG=$(find ~/Library/Developer/Xcode/DerivedData -name "*.log" -type f -mmin -10 2>/dev/null | head -1)
            if [ -n "$XCODE_LOG" ]; then
              echo "Found Xcode log: $XCODE_LOG"
              echo "Last 50 lines with errors:"
              grep -i "error\|failed\|cannot be found" "$XCODE_LOG" | tail -20 || true
            else
              echo "Xcode log not found in DerivedData"
            fi
            
            # Check for privacy manifest errors specifically
            if grep -qi "Build input file cannot be found\|privacy.*bundle" /tmp/flutter_build.log; then
              echo ""
              echo "=========================================="
              echo "PRIVACY MANIFEST ERROR DETECTED!"
              echo "=========================================="
              grep -i "Build input file cannot be found\|privacy.*bundle" /tmp/flutter_build.log | head -10
              echo ""
              echo "Attempting to create missing privacy manifests..."
              create_privacy_manifests
              echo "Created privacy manifests."
            fi
            
            # Show full error context from build log
            echo ""
            echo "=== Full error context (last 200 lines) ==="
            tail -200 /tmp/flutter_build.log | grep -A 5 -B 5 -i "error\|failed\|cannot" || tail -50 /tmp/flutter_build.log
            
            # Check if privacy manifests exist
            echo ""
            echo "=== Checking privacy manifest files ==="
            for pkg in url_launcher_ios sqflite_darwin shared_preferences_foundation share_plus; do
              if [ -f "build/ios/Release-iphoneos/${pkg}/${pkg}_privacy.bundle/${pkg}_privacy" ]; then
                echo "✓ ${pkg} privacy manifest exists"
              else
                echo "✗ ${pkg} privacy manifest NOT found"
              fi
            done
            
            # List all created privacy manifests
            echo ""
            echo "=== All privacy manifest files ==="
            find build/ios/Release-iphoneos -type f -path "*_privacy.bundle/*" -o -path "*_Privacy.bundle/*" -o -path "*.bundle/*" 2>/dev/null | head -30 || echo "No privacy manifest files found"
            
            exit 1
          fi
          
      - name: Verify build artifacts
        script: |
          echo "=========================================="
          echo "Verifying build artifacts..."
          echo "=========================================="
          
          # Check for .app file
          if [ -d "build/ios/Release-iphoneos/Runner.app" ]; then
            echo "✓ Found Runner.app at: build/ios/Release-iphoneos/Runner.app"
            ls -lh build/ios/Release-iphoneos/Runner.app
          elif [ -d "build/ios/iphoneos/Runner.app" ]; then
            echo "✓ Found Runner.app at: build/ios/iphoneos/Runner.app"
            ls -lh build/ios/iphoneos/Runner.app
          else
            echo "✗ Runner.app not found in expected locations"
            echo "Searching for .app files..."
            find build/ios -name "*.app" -type d 2>/dev/null || echo "No .app files found"
          fi
          
          # Check for .ipa file
          if [ -f "build/ios/ipa/*.ipa" ]; then
            echo "✓ Found .ipa file"
            ls -lh build/ios/ipa/*.ipa
          else
            echo "No .ipa file found (expected for --no-codesign build)"
          fi
          
          echo ""
          echo "Build directory structure:"
          ls -la build/ios/ 2>/dev/null || echo "build/ios/ directory not found"
          
      # Uncomment below if you have code signing configured
      # - name: Build iOS IPA (with code signing)
      #   script: |
      #     flutter build ipa --release
          
      # Optional: Run iOS tests
      # - name: Run iOS tests
      #   script: |
      #     cd ios
      #     xcodebuild test \
      #       -workspace Runner.xcworkspace \
      #       -scheme Runner \
      #       -destination 'platform=iOS Simulator,name=iPhone 15' \
      #       -enableCodeCoverage YES \
      #       | xcpretty
          
    artifacts:
      - build/ios/Release-iphoneos/*.app
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - /tmp/flutter_build.log
      
    publishing:
      email:
        recipients:
          - omarlamzah64@gmail.com  # Your email from git config
        notify:
          success: true
          failure: true
      # Uncomment and configure for App Store Connect upload
      # app_store_connect:
      #   auth: integration
      #   submit_to_testflight: false
      #   beta_groups:
      #     - group name 1
      #     - group name 2
      
      # Uncomment for Slack notifications
      # slack:
      #   channel: '#builds'
      #   notify_on_build_start: true
      #   notify:
      #     success: true
      #     failure: true
